[project]
name = 'DGCS'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.civilization-manager]
path = 'contracts/civilization-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.cosmic-event-nft]
path = 'contracts/cosmic-event-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
